export const listData = [
  {
    id: 1,
    title: "The Grand Event Center",
    img: "https://images.pexels.com/photos/15247590/pexels-photo-15247590/free-photo-of-a-large-building-with-a-dome-and-a-ship-in-the-water.jpeg?auto=compress&cs=tinysrgb&w=1260&h=750&dpr=1",
    images: [
      "https://images.pexels.com/photos/8366656/pexels-photo-8366656.jpeg?auto=compress&cs=tinysrgb&w=1260&h=750&dpr=1",
      "https://images.pexels.com/photos/14586964/pexels-photo-14586964.jpeg?auto=compress&cs=tinysrgb&w=400",
      "https://images.pexels.com/photos/14412296/pexels-photo-14412296.jpeg?auto=compress&cs=tinysrgb&w=400",
      "https://images.pexels.com/photos/7168562/pexels-photo-7168562.jpeg?auto=compress&cs=tinysrgb&w=400",
    ],
    address: "65 Main St, District 11, Ho Chi Minh City, Vietnam",
    coordinates: {
      latitude: 10.74582059190319,
      longitude: 106.68846875760043,
    },
    capacity: 930,
    price: 19132406,
    rating: 4.8,
    size: 200,
    description:
      "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Nulla nec purus feugiat, molestie ipsum et, consequat nibh. Etiam non elit dui.",
    features: [
      "Free Wifi",
      "Parking",
      "Air Conditioner",
      "Catering",
      "Sound System",
    ],
    placeType: "inside",
    services: [
      {
        id: 1,
        name: "Catering",
        description: "Food and beverage service",
        price: 1000000,
        img: "https://images.pexels.com/photos/7245482/pexels-photo-7245482.jpeg?auto=compress&cs=tinysrgb&w=400",
      },
      {
        id: 2,
        name: "Photography",
        description: "Professional photography for the event",
        price: 500000,
        img: "https://images.pexels.com/photos/403495/pexels-photo-403495.jpeg?auto=compress&cs=tinysrgb&w=400",
      },
      {
        id: 3,
        name: "DJ/MC",
        description: "Music and event hosting",
        price: 800000,
        img: "https://images.pexels.com/photos/2111016/pexels-photo-2111016.jpeg?auto=compress&cs=tinysrgb&w=400",
      },
      {
        id: 4,
        name: "Decoration",
        description: "Event venue decoration",
        price: 1200000,
        img: "https://images.pexels.com/photos/750843/pexels-photo-750843.jpeg?auto=compress&cs=tinysrgb&w=400",
      },
      {
        id: 5,
        name: "Security",
        description: "Security service for the event",
        price: 400000,
        img: "https://images.pexels.com/photos/1464230/pexels-photo-1464230.jpeg?auto=compress&cs=tinysrgb&w=400",
      },
    ],
    author: {
      id: 1,
      name: "John Doe",
      img: "https://images.pexels.com/photos/29062932/pexels-photo-29062932/free-photo-of-urban-fashion-shoot-with-street-art.jpeg?auto=compress&cs=tinysrgb&w=400&lazy=load",
    },
  },
  {
    id: 2,
    title: "The Loft",
    img: "https://images.pexels.com/photos/1395967/pexels-photo-1395967.jpeg?auto=compress&cs=tinysrgb&w=400",
    images: [
      "https://images.pexels.com/photos/1114425/pexels-photo-1114425.jpeg?auto=compress&cs=tinysrgb&w=400",
      "https://images.pexels.com/photos/1395964/pexels-photo-1395964.jpeg?auto=compress&cs=tinysrgb&w=400",
      "https://images.pexels.com/photos/1123254/pexels-photo-1123254.jpeg?auto=compress&cs=tinysrgb&w=400",
      "https://images.pexels.com/photos/313715/pexels-photo-313715.jpeg?auto=compress&cs=tinysrgb&w=400",
    ],
    address:
      "23 Phan Xich Long St, Phu Nhuan District, Ho Chi Minh City, Vietnam",
    coordinates: {
      latitude: 10.79287059199999,
      longitude: 106.6824924576004,
    },
    capacity: 650,
    price: 15322000,
    rating: 4.5,
    size: 200,
    description:
      "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Nulla nec purus feugiat, molestie ipsum et, consequat nibh. Etiam non elit dui.",
    features: [
      "Free Wifi",
      "Parking",
      "Air Conditioner",
      "Catering",
      "Sound System",
    ],
    placeType: "inside",
    services: [
      {
        id: 1,
        name: "Catering",
        description: "Food and beverage service",
        price: 1000000,
        img: "https://images.pexels.com/photos/29098346/pexels-photo-29098346/free-photo-of-elegant-chocolate-truffles-with-floral-display.jpeg?auto=compress&cs=tinysrgb&w=400",
      },
      {
        id: 2,
        name: "Photography",
        description: "Professional photography for the event",
        price: 500000,
        img: "https://images.pexels.com/photos/167832/pexels-photo-167832.jpeg?auto=compress&cs=tinysrgb&w=400",
      },
      {
        id: 3,
        name: "DJ/MC",
        description: "Music and event hosting",
        price: 800000,
        img: "https://images.pexels.com/photos/860707/pexels-photo-860707.jpeg?auto=compress&cs=tinysrgb&w=400",
      },
    ],
    author: {
      id: 2,
      name: "Jane Smith",
      img: "https://images.pexels.com/photos/27928190/pexels-photo-27928190/free-photo-of-a-woman-in-a-red-head-wrap-and-glasses.jpeg?auto=compress&cs=tinysrgb&w=400&lazy=load",
    },
  },
  {
    id: 3,
    title: "The Garden Pavilion",
    img: "https://images.pexels.com/photos/1709003/pexels-photo-1709003.jpeg?auto=compress&cs=tinysrgb&w=1260&h=750&dpr=1",
    images: [],
    address: "89 Le Loi St, District 1, Ho Chi Minh City, Vietnam",
    coordinates: {
      latitude: 10.775331,
      longitude: 106.700981,
    },
    capacity: 1200,
    price: 22150000,
    rating: 4.9,
    size: 200,
    description:
      "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Nulla nec purus feugiat, molestie ipsum et, consequat nibh. Etiam non elit dui.",
    features: [
      "Free Wifi",
      "Parking",
      "Air Conditioner",
      "Catering",
      "Sound System",
    ],
    placeType: "inside",
    services: [
      {
        id: 1,
        name: "Catering",
        description: "Food and beverage service",
        price: 1000000,
        img: "https://images.pexels.com/photos/6270/woman-flowers-holidays-girl-6270.jpg?auto=compress&cs=tinysrgb&w=400",
      },
      {
        id: 2,
        name: "Photography",
        description: "Professional photography for the event",
        price: 500000,
        img: "https://images.pexels.com/photos/93820/pexels-photo-93820.jpeg?auto=compress&cs=tinysrgb&w=400",
      },
    ],
    author: {
      id: 1,
      name: "John Doe",
      img: "https://images.pexels.com/photos/29062932/pexels-photo-29062932/free-photo-of-urban-fashion-shoot-with-street-art.jpeg?auto=compress&cs=tinysrgb&w=400&lazy=load",
    },
  },
  {
    id: 4,
    title: "The Crystal Ballroom",
    img: "https://images.pexels.com/photos/356065/pexels-photo-356065.jpeg?auto=compress&cs=tinysrgb&w=400",
    images: [],
    address: "45 Pasteur St, District 1, Ho Chi Minh City, Vietnam",
    coordinates: {
      latitude: 10.775839,
      longitude: 106.700859,
    },
    capacity: 900,
    price: 19500000,
    rating: 4.7,
    size: 200,
    description:
      "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Nulla nec purus feugiat, molestie ipsum et, consequat nibh. Etiam non elit dui.",
    features: [
      "Free Wifi",
      "Parking",
      "Air Conditioner",
      "Catering",
      "Sound System",
    ],
    placeType: "inside",
    services: [
      {
        id: 1,
        name: "Catering",
        description: "Food and beverage service",
        price: 1000000,
        img: "https://images.pexels.com/photos/29098346/pexels-photo-29098346/free-photo-of-elegant-chocolate-truffles-with-floral-display.jpeg?auto=compress&cs=tinysrgb&w=400",
      },
      {
        id: 2,
        name: "Photography",
        description: "Professional photography for the event",
        price: 500000,
        img: "https://images.pexels.com/photos/167832/pexels-photo-167832.jpeg?auto=compress&cs=tinysrgb&w=400",
      },
      {
        id: 3,
        name: "DJ/MC",
        description: "Music and event hosting",
        price: 800000,
        img: "https://images.pexels.com/photos/860707/pexels-photo-860707.jpeg?auto=compress&cs=tinysrgb&w=400",
      },
    ],
    author: {
      id: 3,
      name: "Bob Johnson",
      img: "https://images.pexels.com/photos/220453/pexels-photo-220453.jpeg?auto=compress&cs=tinysrgb&w=400&lazy=load",
    },
  },
  {
    id: 5,
    title: "The Harborside",
    img: "https://images.pexels.com/photos/18511192/pexels-photo-18511192/free-photo-of-palermo.jpeg?auto=compress&cs=tinysrgb&w=400",
    images: [],
    address: "102 Nguyen Van Cu St, District 5, Ho Chi Minh City, Vietnam",
    coordinates: {
      latitude: 10.762622,
      longitude: 106.682994,
    },
    capacity: 750,
    price: 18520000,
    rating: 4.6,
    size: 200,
    description:
      "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Nulla nec purus feugiat, molestie ipsum et, consequat nibh. Etiam non elit dui.",
    features: [
      "Free Wifi",
      "Parking",
      "Air Conditioner",
      "Catering",
      "Sound System",
    ],
    placeType: "inside",
    services: [
      {
        id: 1,
        name: "Catering",
        description: "Food and beverage service",
        price: 1000000,
        img: "",
      },
      {
        id: 2,
        name: "Photography",
        description: "Professional photography for the event",
        price: 500000,
        img: "",
      },
    ],
    author: {
      id: 3,
      name: "Bob Johnson",
      img: "https://images.pexels.com/photos/220453/pexels-photo-220453.jpeg?auto=compress&cs=tinysrgb&w=400&lazy=load",
    },
  },
  {
    id: 6,
    title: "The Gallery",
    img: "https://images.pexels.com/photos/2041556/pexels-photo-2041556.jpeg?auto=compress&cs=tinysrgb&w=400",
    images: [],
    address:
      "97 Dien Bien Phu St, Binh Thanh District, Ho Chi Minh City, Vietnam",
    coordinates: {
      latitude: 10.801445,
      longitude: 106.718825,
    },
    capacity: 850,
    price: 17250000,
    rating: 4.4,
    size: 200,
    description:
      "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Nulla nec purus feugiat, molestie ipsum et, consequat nibh. Etiam non elit dui.",
    features: [
      "Free Wifi",
      "Parking",
      "Air Conditioner",
      "Catering",
      "Sound System",
    ],
    placeType: "inside",
    services: [
      {
        id: 1,
        name: "Catering",
        description: "Food and beverage service",
        price: 1000000,
        img: "https://images.pexels.com/photos/29098346/pexels-photo-29098346/free-photo-of-elegant-chocolate-truffles-with-floral-display.jpeg?auto=compress&cs=tinysrgb&w=400",
      },
      {
        id: 2,
        name: "Photography",
        description: "Professional photography for the event",
        price: 500000,
        img: "https://images.pexels.com/photos/167832/pexels-photo-167832.jpeg?auto=compress&cs=tinysrgb&w=400",
      },
      {
        id: 3,
        name: "DJ/MC",
        description: "Music and event hosting",
        price: 800000,
        img: "https://images.pexels.com/photos/860707/pexels-photo-860707.jpeg?auto=compress&cs=tinysrgb&w=400",
      },
    ],
    author: {
      id: 3,
      name: "Bob Johnson",
      img: "https://images.pexels.com/photos/220453/pexels-photo-220453.jpeg?auto=compress&cs=tinysrgb&w=400&lazy=load",
    },
  },
  {
    id: 7,
    title: "The Terrace",
    img: "https://images.pexels.com/photos/1123982/pexels-photo-1123982.jpeg?auto=compress&cs=tinysrgb&w=400",
    images: [],
    address: "120 Vo Van Tan St, District 3, Ho Chi Minh City, Vietnam",
    coordinates: {
      latitude: 10.777884,
      longitude: 106.694317,
    },
    capacity: 600,
    price: 16830000,
    rating: 4.3,
    size: 200,
    description:
      "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Nulla nec purus feugiat, molestie ipsum et, consequat nibh. Etiam non elit dui.",
    features: [
      "Free Wifi",
      "Parking",
      "Air Conditioner",
      "Catering",
      "Sound System",
    ],
    placeType: "inside",
    services: [
      {
        id: 1,
        name: "Catering",
        description: "Food and beverage service",
        price: 1000000,
        img: "https://images.pexels.com/photos/29098346/pexels-photo-29098346/free-photo-of-elegant-chocolate-truffles-with-floral-display.jpeg?auto=compress&cs=tinysrgb&w=400",
      },
      {
        id: 2,
        name: "Photography",
        description: "Professional photography for the event",
        price: 500000,
        img: "https://images.pexels.com/photos/167832/pexels-photo-167832.jpeg?auto=compress&cs=tinysrgb&w=400",
      },
      {
        id: 3,
        name: "DJ/MC",
        description: "Music and event hosting",
        price: 800000,
        img: "https://images.pexels.com/photos/860707/pexels-photo-860707.jpeg?auto=compress&cs=tinysrgb&w=400",
      },
    ],
    author: {
      id: 4,
      name: "Alice Brown",
      img: "https://images.pexels.com/photos/28054435/pexels-photo-28054435/free-photo-of-a-woman-in-a-park.jpeg?auto=compress&cs=tinysrgb&w=400&lazy=load",
    },
  },
  {
    id: 8,
    title: "The Pavilion",
    img: "https://images.pexels.com/photos/3937730/pexels-photo-3937730.jpeg?auto=compress&cs=tinysrgb&w=400",
    images: [],
    address: "75 Nguyen Trai St, District 1, Ho Chi Minh City, Vietnam",
    coordinates: {
      latitude: 10.771616,
      longitude: 106.699413,
    },
    capacity: 500,
    price: 14000000,
    rating: 4.1,
    size: 200,
    description:
      "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Nulla nec purus feugiat, molestie ipsum et, consequat nibh. Etiam non elit dui.",
    features: [
      "Free Wifi",
      "Parking",
      "Air Conditioner",
      "Catering",
      "Sound System",
    ],
    placeType: "inside",
    services: [
      {
        id: 1,
        name: "Catering",
        description: "Food and beverage service",
        price: 1000000,
        img: "https://images.pexels.com/photos/29098346/pexels-photo-29098346/free-photo-of-elegant-chocolate-truffles-with-floral-display.jpeg?auto=compress&cs=tinysrgb&w=400",
      },
      {
        id: 2,
        name: "Photography",
        description: "Professional photography for the event",
        price: 500000,
        img: "https://images.pexels.com/photos/167832/pexels-photo-167832.jpeg?auto=compress&cs=tinysrgb&w=400",
      },
      {
        id: 3,
        name: "DJ/MC",
        description: "Music and event hosting",
        price: 800000,
        img: "https://images.pexels.com/photos/860707/pexels-photo-860707.jpeg?auto=compress&cs=tinysrgb&w=400",
      },
    ],
    author: {
      id: 4,
      name: "Alice Brown",
      img: "https://images.pexels.com/photos/28054435/pexels-photo-28054435/free-photo-of-a-woman-in-a-park.jpeg?auto=compress&cs=tinysrgb&w=400&lazy=load",
    },
  },
  {
    id: 9,
    title: "The Atrium",
    img: "https://images.pexels.com/photos/3779816/pexels-photo-3779816.jpeg?auto=compress&cs=tinysrgb&w=400",
    images: [],
    address:
      "35 Nguyen Thi Minh Khai St, District 1, Ho Chi Minh City, Vietnam",
    coordinates: {
      latitude: 10.777275,
      longitude: 106.695911,
    },
    capacity: 1250,
    price: 24000000,
    rating: 4.9,
    size: 200,
    description:
      "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Nulla nec purus feugiat, molestie ipsum et, consequat nibh. Etiam non elit dui.",
    features: [
      "Free Wifi",
      "Parking",
      "Air Conditioner",
      "Catering",
      "Sound System",
    ],
    placeType: "inside",
    services: [
      {
        id: 1,
        name: "Catering",
        description: "Food and beverage service",
        price: 1000000,
        img: "",
      },
      {
        id: 2,
        name: "Photography",
        description: "Professional photography for the event",
        price: 500000,
        img: "",
      },
    ],
    author: {
      id: 4,
      name: "Alice Brown",
      img: "https://images.pexels.com/photos/28054435/pexels-photo-28054435/free-photo-of-a-woman-in-a-park.jpeg?auto=compress&cs=tinysrgb&w=400&lazy=load",
    },
  },
  {
    id: 10,
    title: "The Courtyard ",
    img: "https://images.pexels.com/photos/337933/pexels-photo-337933.jpeg?auto=compress&cs=tinysrgb&w=400",
    images: [],
    address: "58 Nguyen Hue St, District 1, Ho Chi Minh City, Vietnam",
    coordinates: {
      latitude: 10.773377,
      longitude: 106.704038,
    },
    capacity: 1400,
    price: 26000000,
    rating: 5.0,
    size: 200,
    description:
      "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Nulla nec purus feugiat, molestie ipsum et, consequat nibh. Etiam non elit dui.",
    features: [
      "Free Wifi",
      "Parking",
      "Air Conditioner",
      "Catering",
      "Sound System",
    ],
    placeType: "inside",
    services: [
      {
        id: 1,
        name: "Catering",
        description: "Food and beverage service",
        price: 1000000,
        img: "",
      },
      {
        id: 2,
        name: "Photography",
        description: "Professional photography for the event",
        price: 500000,
        img: "",
      },
    ],
    author: {
      id: 5,
      name: "Michael Scott",
      img: "https://images.pexels.com/photos/29062946/pexels-photo-29062946/free-photo-of-young-man-in-blue-shirt-under-sunlight.jpeg?auto=compress&cs=tinysrgb&w=400&lazy=load",
    },
  },
  {
    id: 11,
    title: "The Summit",
    img: "https://images.pexels.com/photos/2774556/pexels-photo-2774556.jpeg?auto=compress&cs=tinysrgb&w=400",
    images: [],
    address: "84 Le Duan St, District 1, Ho Chi Minh City, Vietnam",
    coordinates: {
      latitude: 10.779719,
      longitude: 106.698076,
    },
    capacity: 950,
    price: 19800000,
    rating: 4.8,
    size: 200,
    description:
      "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Nulla nec purus feugiat, molestie ipsum et, consequat nibh. Etiam non elit dui.",
    features: [
      "Free Wifi",
      "Parking",
      "Air Conditioner",
      "Catering",
      "Sound System",
    ],
    placeType: "inside",
    services: [
      {
        id: 1,
        name: "Catering",
        description: "Food and beverage service",
        price: 1000000,
        img: "",
      },
      {
        id: 2,
        name: "Photography",
        description: "Professional photography for the event",
        price: 500000,
        img: "",
      },
    ],
    author: {
      id: 5,
      name: "Michael Scott",
      img: "https://images.pexels.com/photos/29062946/pexels-photo-29062946/free-photo-of-young-man-in-blue-shirt-under-sunlight.jpeg?auto=compress&cs=tinysrgb&w=400&lazy=load",
    },
  },
  {
    id: 12,
    title: "The Oasis",
    img: "https://images.pexels.com/photos/3320461/pexels-photo-3320461.jpeg?auto=compress&cs=tinysrgb&w=1260&h=750&dpr=1",
    images: [],
    address: "12 Pham Hong Thai St, District 1, Ho Chi Minh City, Vietnam",
    coordinates: {
      latitude: 10.774431,
      longitude: 106.694991,
    },
    capacity: 1150,
    price: 23500000,
    rating: 4.9,
    size: 200,
    description:
      "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Nulla nec purus feugiat, molestie ipsum et, consequat nibh. Etiam non elit dui.",
    features: [
      "Free Wifi",
      "Parking",
      "Air Conditioner",
      "Catering",
      "Sound System",
    ],
    placeType: "inside",
    services: [
      {
        id: 1,
        name: "Catering",
        description: "Food and beverage service",
        price: 1000000,
        img: "",
      },
      {
        id: 2,
        name: "Photography",
        description: "Professional photography for the event",
        price: 500000,
        img: "",
      },
    ],
    author: {
      id: 5,
      name: "Michael Scott",
      img: "https://images.pexels.com/photos/29062946/pexels-photo-29062946/free-photo-of-young-man-in-blue-shirt-under-sunlight.jpeg?auto=compress&cs=tinysrgb&w=400&lazy=load",
    },
  },
];

export const singlePostData = {};

export const userData = [
  {
    id: 1,
    name: "John Doe",
    img: "https://images.pexels.com/photos/13969614/pexels-photo-13969614.jpeg?auto=compress&cs=tinysrgb&w=400",
    email: "john@gmail.com",
    password: "123456",
  },
  {
    id: 2,
    name: "Jane Smith",
    img: "https://images.pexels.com/photos/415829/pexels-photo-415829.jpeg?auto=compress&cs=tinysrgb&w=400",
    email: "jane.smith@gmail.com",
    password: "abcdef",
  },
  {
    id: 3,
    name: "Bob Johnson",
    img: "https://images.pexels.com/photos/220453/pexels-photo-220453.jpeg?auto=compress&cs=tinysrgb&w=400",
    email: "bob.johnson@gmail.com",
    password: "qwerty",
  },
  {
    id: 4,
    name: "Alice Brown",
    img: "https://images.pexels.com/photos/774909/pexels-photo-774909.jpeg?auto=compress&cs=tinysrgb&w=400",
    email: "alice.brown@gmail.com",
    password: "password",
  },
  {
    id: 5,
    name: "Michael Scott",
    img: "https://images.pexels.com/photos/91227/pexels-photo-91227.jpeg?auto=compress&cs=tinysrgb&w=400",
    email: "michael.scott@gmail.com",
    password: "dundermifflin",
  },
  {
    id: 6,
    name: "Pam Beesly",
    img: "https://images.pexels.com/photos/20787/pexels-photo.jpg?auto=compress&cs=tinysrgb&w=400",
    email: "pam.beesly@gmail.com",
    password: "jimhalpert",
  },
  {
    id: 7,
    name: "Jim Halpert",
    img: "https://images.pexels.com/photos/614810/pexels-photo-614810.jpeg?auto=compress&cs=tinysrgb&w=400",
    email: "jim.halpert@gmail.com",
    password: "pamforever",
  },
  {
    id: 8,
    name: "Dwight Schrute",
    img: "https://images.pexels.com/photos/91224/pexels-photo-91224.jpeg?auto=compress&cs=tinysrgb&w=400",
    email: "dwight.schrute@gmail.com",
    password: "beets123",
  },
  {
    id: 9,
    name: "Angela Martin",
    img: "https://images.pexels.com/photos/458649/pexels-photo-458649.jpeg?auto=compress&cs=tinysrgb&w=400",
    email: "angela.martin@gmail.com",
    password: "catslover",
  },
  {
    id: 10,
    name: "Stanley Hudson",
    img: "https://images.pexels.com/photos/2379005/pexels-photo-2379005.jpeg?auto=compress&cs=tinysrgb&w=400",
    email: "stanley.hudson@gmail.com",
    password: "pretzelday",
  },
  {
    id: 11,
    name: "Kevin Malone",
    img: "https://images.pexels.com/photos/733872/pexels-photo-733872.jpeg?auto=compress&cs=tinysrgb&w=400",
    email: "kevin.malone@gmail.com",
    password: "chilis123",
  },
  {
    id: 12,
    name: "Ryan Howard",
    img: "https://images.pexels.com/photos/936734/pexels-photo-936734.jpeg?auto=compress&cs=tinysrgb&w=400",
    email: "ryan.howard@gmail.com",
    password: "temp123",
  },
  {
    id: 13,
    name: "Kelly Kapoor",
    img: "https://images.pexels.com/photos/415829/pexels-photo-415829.jpeg?auto=compress&cs=tinysrgb&w=400",
    email: "kelly.kapoor@gmail.com",
    password: "fashionista",
  },
  {
    id: 14,
    name: "Oscar Martinez",
    img: "https://images.pexels.com/photos/1138903/pexels-photo-1138903.jpeg?auto=compress&cs=tinysrgb&w=400",
    email: "oscar.martinez@gmail.com",
    password: "accountant",
  },
  {
    id: 15,
    name: "Meredith Palmer",
    img: "https://images.pexels.com/photos/2379004/pexels-photo-2379004.jpeg?auto=compress&cs=tinysrgb&w=400",
    email: "meredith.palmer@gmail.com",
    password: "party123",
  },
];

export const chatData = [
  {
    id: 1,
    name: "Bob Johnson",
    img: "https://images.pexels.com/photos/1681010/pexels-photo-1681010.jpeg?auto=compress&cs=tinysrgb&w=400",
    chat: [
      { id: 1, text: "Hi, how are you?", time: "12:00", own: true },
      { id: 2, text: "Hello, I am fine", time: "12:01", own: false },
      { id: 3, text: "What can I do for you?", time: "12:02", own: true },
      { id: 4, text: "I need some information.", time: "12:03", own: false },
    ],
  },
  {
    id: 2,
    name: "Mary Smith",
    img: "https://images.pexels.com/photos/733872/pexels-photo-733872.jpeg?auto=compress&cs=tinysrgb&w=400",
    chat: [
      { id: 1, text: "Hi, how are you?", time: "12:00", own: true },
      { id: 2, text: "Hello, I am fine", time: "12:01", own: false },
      { id: 3, text: "What can I do for you?", time: "12:02", own: true },
      { id: 4, text: "I need some information.", time: "12:03", own: false },
    ],
  },
  {
    id: 3,
    name: "Alice Brown",
    img: "https://images.pexels.com/photos/13969614/pexels-photo-13969614.jpeg?auto=compress&cs=tinysrgb&w=400",
    chat: [
      { id: 1, text: "Hi, I need some thing", time: "12:00", own: false },
      { id: 2, text: "Sure, what do you need?", time: "12:01", own: true },
    ],
  },
  {
    id: 4,
    name: "Attila",
    img: "https://images.pexels.com/photos/13969614/pexels-photo-13969614.jpeg?auto=compress&cs=tinysrgb&w=400",
    chat: [
      { id: 1, text: "Hi, I need some thing", time: "12:00", own: false },
      { id: 2, text: "Sure, what do you need?", time: "12:01", own: true },
      { id: 3, text: "I need some information.", time: "12:03", own: false },
      { id: 4, text: "I need some information.", time: "12:03", own: false },
    ],
  },
];

export const orderData = [
  {
    id: 1,
    venue: "The Grand Event Center",
    img: "https://images.pexels.com/photos/15247590/pexels-photo-15247590/free-photo-of-a-large-building-with-a-dome-and-a-ship-in-the-water.jpeg?auto=compress&cs=tinysrgb&w=1260&h=750&dpr=1",
    address: "65 Main St, District 11, Ho Chi Minh City, Vietnam",
    eventDate: "2024-12-15",
    guestCount: 150,
    totalCost: 5000000,
    status: ["Booking", "Confirmation", "Payment"],
    bookingDate: "2024-10-01",
    paymentMethod: "Credit Card",
    notes: "Need extra decoration.",
    services: [
      { id: 1, name: "Catering" },
      { id: 2, name: "Photography" },
    ],
  },
  {
    id: 2,
    venue: "The Loft",
    img: "https://images.pexels.com/photos/1395967/pexels-photo-1395967.jpeg?auto=compress&cs=tinysrgb&w=400",
    address:
      "23 Phan Xich Long St, Phu Nhuan District, Ho Chi Minh City, Vietnam",
    eventDate: "2024-11-20",
    guestCount: 300,
    totalCost: 10000000,
    status: [
      "Booking",
      "Confirmation",
      "Payment",
      "Preparation",
      "Event",
      "Post-Event",
      "Follow-up",
    ],
    services: [
      { id: 1, name: "Catering" },
      { id: 2, name: "Photography" },
      { id: 3, name: "DJ/MC" },
      { id: 4, name: "Decoration" },
      { id: 5, name: "Security" },
    ],
    bookingDate: "2024-09-25",
    paymentMethod: "Bank Transfer",
    notes: "Require AV equipment.",
  },
];

export const orderDataAdmin = [
  {
    id: 1,
    customerName: "John Doe",
    eventDate: "2024-12-15",
    venue: "Grand Ballroom",
    guestCount: 150,
    totalCost: 5000000,
    status: ["Booking", "Confirmation", "Payment"],
    bookingDate: "2024-10-01",
    paymentMethod: "Credit Card",
    notes: "Need extra decoration.",
    services: ["Catering", "Photography"],
    img: "https://images.pexels.com/photos/26898886/pexels-photo-26898886/free-photo-of-people-sitting-outdoors.jpeg?auto=compress&cs=tinysrgb&w=1260&h=750&dpr=1",
  },
  {
    id: 2,
    customerName: "Jane Smith",
    review: "Corporate Annual Meeting",
    eventDate: "2024-11-20",
    venue: "Conference Hall",
    guestCount: 300,
    totalCost: 10000000,
    status: [
      "Booking",
      "Confirmation",
      "Payment",
      "Preparation",
      "Event",
      "Post-Event",
      "Follow-up",
    ],
    services: ["Catering", "Photography", "DJ/MC", "Decoration", "Security"],
    bookingDate: "2024-09-25",
    paymentMethod: "Bank Transfer",
    notes: "Require AV equipment.",
    img: "https://images.pexels.com/photos/26898886/pexels-photo-26898886/free-photo-of-people-sitting-outdoors.jpeg?auto=compress&cs=tinysrgb&w=1260&h=750&dpr=1",
  },
  {
    id: 3,
    customerName: "Emily Johnson",
    review: "Birthday Party",
    eventDate: "2024-12-05",
    venue: "Garden Area",
    guestCount: 50,
    totalCost: 2000000,
    status: ["Booking", "Confirmation"],
    services: ["Catering", "Photography", "DJ/MC", "Decoration"],
    bookingDate: "2024-10-05",
    paymentMethod: "Cash",
    notes: "Theme: Tropical.",
    img: "https://images.pexels.com/photos/26898886/pexels-photo-26898886/free-photo-of-people-sitting-outdoors.jpeg?auto=compress&cs=tinysrgb&w=1260&h=750&dpr=1",
  },
  {
    id: 4,
    customerName: "Michael Brown",
    review: "Product Launch",
    eventDate: "2024-11-10",
    venue: "Convention Center",
    guestCount: 200,
    totalCost: 8000000,
    status: ["Booking", "Confirmation", "Payment", "Preparation"],
    bookingDate: "2024-09-15",
    paymentMethod: "Credit Card",
    notes: "Requires promotional materials.",
    img: "https://images.pexels.com/photos/26898886/pexels-photo-26898886/free-photo-of-people-sitting-outdoors.jpeg?auto=compress&cs=tinysrgb&w=1260&h=750&dpr=1",
  },
  {
    id: 5,
    customerName: "Sarah Wilson",
    review: "Charity Gala",
    eventDate: "2024-12-20",
    venue: "Grand Ballroom",
    guestCount: 400,
    totalCost: 15000000,
    status: ["Booking", "Confirmation", "Payment", "Preparation", "Event"],
    bookingDate: "2024-09-30",
    paymentMethod: "Bank Transfer",
    notes: "Special guest appearance.",
    img: "https://images.pexels.com/photos/26898886/pexels-photo-26898886/free-photo-of-people-sitting-outdoors.jpeg?auto=compress&cs=tinysrgb&w=1260&h=750&dpr=1",
  },
  {
    id: 6,
    customerName: "David Taylor",
    review: "Networking Event",
    eventDate: "2024-11-15",
    venue: "Lounge Area",
    guestCount: 100,
    totalCost: 4000000,
    status: ["Booking", "Confirmation", "Payment"],
    bookingDate: "2024-10-02",
    paymentMethod: "Credit Card",
    notes: "Refreshments required.",
    img: "https://images.pexels.com/photos/26898886/pexels-photo-26898886/free-photo-of-people-sitting-outdoors.jpeg?auto=compress&cs=tinysrgb&w=1260&h=750&dpr=1",
  },
  {
    id: 7,
    customerName: "Laura Miller",
    review: "Graduation Ceremony",
    eventDate: "2024-11-25",
    venue: "Auditorium",
    guestCount: 250,
    totalCost: 6000000,
    status: ["Booking", "Confirmation", "Payment", "Preparation", "Event"],
    bookingDate: "2024-09-10",
    paymentMethod: "Cash",
    notes: "Need a projector.",
    img: "https://images.pexels.com/photos/26898886/pexels-photo-26898886/free-photo-of-people-sitting-outdoors.jpeg?auto=compress&cs=tinysrgb&w=1260&h=750&dpr=1",
  },
  {
    id: 8,
    customerName: "James Anderson",
    review: "Team Building Retreat",
    eventDate: "2024-10-30",
    venue: "Outdoor Park",
    guestCount: 75,
    totalCost: 3500000,
    status: ["Booking", "Confirmation", "Payment"],
    bookingDate: "2024-10-01",
    paymentMethod: "Credit Card",
    notes: "Include team activities.",
    img: "https://images.pexels.com/photos/26898886/pexels-photo-26898886/free-photo-of-people-sitting-outdoors.jpeg?auto=compress&cs=tinysrgb&w=1260&h=750&dpr=1",
  },
  {
    id: 9,
    customerName: "Jessica Harris",
    review: "Anniversary Celebration",
    eventDate: "2024-12-01",
    venue: "Private Villa",
    guestCount: 60,
    totalCost: 3000000,
    status: ["Booking", "Confirmation", "Payment", "Preparation"],
    bookingDate: "2024-10-03",
    paymentMethod: "Bank Transfer",
    notes: "Catering needed.",
    img: "https://images.pexels.com/photos/26898886/pexels-photo-26898886/free-photo-of-people-sitting-outdoors.jpeg?auto=compress&cs=tinysrgb&w=1260&h=750&dpr=1",
  },
  {
    id: 10,
    customerName: "Robert Young",
    review: "Workshop on Innovation",
    eventDate: "2024-11-05",
    venue: "Training Room",
    guestCount: 40,
    totalCost: 2500000,
    status: ["Booking", "Confirmation", "Payment"],
    bookingDate: "2024-09-20",
    paymentMethod: "Cash",
    notes: "Materials to be provided.",
    img: "https://images.pexels.com/photos/26898886/pexels-photo-26898886/free-photo-of-people-sitting-outdoors.jpeg?auto=compress&cs=tinysrgb&w=1260&h=750&dpr=1",
  },
];

export const services = [
  {
    id: 1,
    name: "Catering",
    description: "Food and beverage service",
    price: 1000000,
  },
  {
    id: 2,
    name: "Photography",
    description: "Professional photography for the event",
    price: 500000,
  },
  {
    id: 3,
    name: "DJ/MC",
    description: "Music and event hosting",
    price: 800000,
  },
  {
    id: 4,
    name: "Decoration",
    description: "Event venue decoration",
    price: 1200000,
  },
  {
    id: 5,
    name: "Security",
    description: "Security service for the event",
    price: 400000,
  },
];
